---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  init.sh: |-
    #!/bin/bash
    set -e
    set -x

    echo "Running init"
    NIFI_BROKER_ID=${HOSTNAME##*-}
    LABELS="nifi-broker-id=$NIFI_BROKER_ID"

    kubectl label pods ${POD_NAME} $LABELS || echo "Failed to label $POD_NAMESPACE.$POD_NAME - RBAC issue?"