---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        #https://github.com/solsson/dockerfiles/tree/master/initutils
        # this is what labels the NIFI pod members so they can be selected
        # this can also be done outside of the cluster if desired
      - name: init-config
        image: solsson/kafka:initutils@sha256:8988aca5b34feabe8d7d4e368f74b2ede398f692c7e99a38b262a938d475812c
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ['/bin/bash', '/etc/kafka-configmap/init.sh']
        volumeMounts:
        - name: configmap
          mountPath: /etc/kafka-configmap
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - containerPort: 80
              name: web
      volumes:
        - name: configmap
          configMap:
            name: broker-config
